
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: dtwrj-vjyvj4

spec:
  backoffLimit: 0
  entrypoint: python actorserve.py #入口命令

  rayClusterSpec:
    rayVersion: "2.50.1"
    headGroupSpec:
      serviceType: NodePort
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        metadata: {}
        spec:
          containers:
          - image: 10.156.168.113:7887/pytorch/ray:latest-py312-cu128
            name: ray-head
            command: ["/bin/bash", "-c", "--"]
            args:
              - |
                cd ~;
                pip install grpcio grpcio-tools;
                pip install git+https://github.com/Tianwen10532/dtw.git;

                read -r -d '' SCRIPT << EOM
                import ray
                from dtw.proxy.grpc.servicer import serve
                from dtw.grpc.invoke import invoke_pb2_grpc as invoke_pb2_grpc
                import time
                @ray.remote
                class F4:
                    def add(self,a,b):
                        logger.info(f"F3 mulval({a},{b})")
                        return a+b
                actor_cls=F4
                serve(actor_cls,addr="0.0.0.0:50051", rcv_addr="0.0.0.0:50052")

                EOM
                printf "%s" "$SCRIPT" > "actorserve.py";

                ulimit -n 65536; echo head; $KUBERAY_GEN_RAY_START_CMD
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            - containerPort: 50051   # <-- gRPC 服务端口
              name: invoke
            - containerPort: 50052
              name: receiver
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"
    workerGroupSpecs:
    - groupName: small-group
      maxReplicas: 5
      minReplicas: 1
      numOfHosts: 1
      rayStartParams: {}
      replicas: 1
      scaleStrategy: {}
      template:
        metadata: {}
        spec:
          containers:
          - image: 10.156.168.113:7887/pytorch/ray:latest-py312-cu128
            name: ray-worker
            command: ["/bin/bash", "-c", "--"]
            args:
              - |
                pip install grpcio grpcio-tools;
                pip install git+https://github.com/Tianwen10532/dtw.git;
                ulimit -n 65536; echo worker; $KUBERAY_GEN_RAY_START_CMD
                tail -f /dev/null
            resources:
              requests:
                cpu: "1"
                
  # runtimeEnvYAML: |
  #   pip:
  #     - requests==2.26.0
  #     - pendulum==2.1.2
  #   env_vars:
  #     counter_name: "test_counter"
  shutdownAfterJobFinishes: true
  submissionMode: K8sJobMode
  ttlSecondsAfterFinished: 10
  