# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: invoke.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'invoke.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cinvoke.proto\"<\n\x11StartActorRequest\x12\x12\n\nactor_name\x18\x01 \x01(\t\x12\x13\n\x0b\x61rgs_pickle\x18\x02 \x01(\x0c\"H\n\x12StartActorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nactor_name\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"H\n\rInvokeRequest\x12\x12\n\nactor_name\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x13\n\x0b\x61rgs_pickle\x18\x03 \x01(\x0c\"E\n\x0eInvokeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08ObjectID\x18\x02 \x01(\t\x12\x10\n\x08SrcParty\x18\x03 \x01(\t2k\n\x07Invoker\x12\x35\n\nStartActor\x12\x12.StartActorRequest\x1a\x13.StartActorResponse\x12)\n\x06Invoke\x12\x0e.InvokeRequest\x1a\x0f.InvokeResponseB\x03\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'invoke_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_STARTACTORREQUEST']._serialized_start=16
  _globals['_STARTACTORREQUEST']._serialized_end=76
  _globals['_STARTACTORRESPONSE']._serialized_start=78
  _globals['_STARTACTORRESPONSE']._serialized_end=150
  _globals['_INVOKEREQUEST']._serialized_start=152
  _globals['_INVOKEREQUEST']._serialized_end=224
  _globals['_INVOKERESPONSE']._serialized_start=226
  _globals['_INVOKERESPONSE']._serialized_end=295
  _globals['_INVOKER']._serialized_start=297
  _globals['_INVOKER']._serialized_end=404
# @@protoc_insertion_point(module_scope)
