apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: dtw-rayjob-example

spec:
  backoffLimit: 0
  entrypoint: python actorserve.py

  rayClusterSpec:
    rayVersion: "2.50.1"
    headGroupSpec:
      serviceType: NodePort
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        metadata: {}
        spec:
          containers:
          - image: 10.156.168.113:7887/pytorch/ray:py312-cu128-deps
            name: ray-head
            command: ["/bin/bash", "-c", "--"]
            args:
              - |
                cd ~;

                read -r -d '' SCRIPT << EOM
                import ray
                import dtw
                from dtw.proxy.grpc.servicer import serve
                from dtw.grpc.invoke import invoke_pb2_grpc as invoke_pb2_grpc
                import time

                # Keep original @dtw.remote source for compatibility/debug.
                @dtw.remote
                class AddWorker:
                    def __init__(self, accu: int):
                        self.accu = accu

                    def add(self, input: int) -> int:
                        input = int(input)
                        self.accu += input
                        return self.accu

                    def double(self, input: int) -> int:
                        input = int(input)
                        return input * 2

                # Runtime actor class renamed to avoid class-name conflict.
                @ray.remote
                class AddWorkerRayRuntime:
                    def __init__(self, accu: int):
                        self.accu = accu

                    def add(self, input: int) -> int:
                        input = int(input)
                        self.accu += input
                        return self.accu

                    def double(self, input: int) -> int:
                        input = int(input)
                        return input * 2

                actor_cls = AddWorkerRayRuntime
                serve(actor_cls, addr="0.0.0.0:50051", rcv_addr="0.0.0.0:50052")
                EOM

                printf "%s" "$SCRIPT" > "actorserve.py";
                ulimit -n 65536; echo head; $KUBERAY_GEN_RAY_START_CMD
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            - containerPort: 50051
              name: invoke
            - containerPort: 50052
              name: receiver
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"
    workerGroupSpecs:
    - groupName: small-group
      maxReplicas: 5
      minReplicas: 1
      numOfHosts: 1
      rayStartParams: {}
      replicas: 1
      scaleStrategy: {}
      template:
        metadata: {}
        spec:
          containers:
          - image: 10.156.168.113:7887/pytorch/ray:py312-cu128-deps
            name: ray-worker
            command: ["/bin/bash", "-c", "--"]
            args:
              - |
                ulimit -n 65536; echo worker; $KUBERAY_GEN_RAY_START_CMD
                tail -f /dev/null
            resources:
              requests:
                cpu: "1"

  runtimeEnvYAML: |
    pip:
      - grpcio==1.75.1
      - grpcio-tools==1.75.1
      - git+https://github.com/Tianwen10532/dtw.git

  shutdownAfterJobFinishes: true
  submissionMode: K8sJobMode
  ttlSecondsAfterFinished: 10
