
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: dtw-rayjob

spec:
  backoffLimit: 0
  entrypoint: python actorserve.py #入口命令

  rayClusterSpec:
    rayVersion: "2.50.1"
    headGroupSpec:
      serviceType: NodePort
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        metadata: {}
        spec:
          containers:
          - image: 10.156.168.113:7887/pytorch/ray:latest-py312-cu128
            name: ray-head
            command: ["/bin/bash", "-c", "--"]
            args:
              - |
                cd ~;
                pip install grpcio grpcio-tools;
                pip install git+https://github.com/Tianwen10532/dtw.git;

                read -r -d '' SCRIPT << EOM
                import grpc
                from concurrent import futures
                import ray
                from dtw.proxy.grpc.servicer import InvokerServicer
                import dtw.grpc.invoke.invoke_pb2_grpc as invoke_pb2_grpc
                @ray.remote
                class AddWorker:
                    def __init__(self, accu:int):
                        self.accu=accu;
                    def add(self, input:int) -> int:
                        input = int(input)
                        # time.sleep(10)
                        self.accu+=input
                        # return str(input+1)
                        return self.accu
                    def double(self, input:int) -> int:
                        input=int(input)
                        # time.sleep(10)
                        return input*2
                actor_cls = AddWorker
                def serve(addr="0.0.0.0:50051"):
                    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
                    invoke_pb2_grpc.add_InvokerServicer_to_server(InvokerServicer(actor_cls), server)
                    server.add_insecure_port(addr)
                    server.start()
                    print(f"gRPC server started on {addr}")
                    server.wait_for_termination()
                serve()

                EOM
                printf "%s" "$SCRIPT" > "actorserve.py";

                ulimit -n 65536; echo head; $KUBERAY_GEN_RAY_START_CMD
              
                
                
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            - containerPort: 50051   # <-- gRPC 服务端口
              name: grpc
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"
    workerGroupSpecs:
    - groupName: small-group
      maxReplicas: 5
      minReplicas: 1
      numOfHosts: 1
      rayStartParams: {}
      replicas: 1
      scaleStrategy: {}
      template:
        metadata: {}
        spec:
          containers:
          - image: 10.156.168.113:7887/pytorch/ray:latest-py312-cu128
            name: ray-worker
            command: ["/bin/bash", "-c", "--"]
            args:
              - |
                pip install grpcio grpcio-tools;
                pip install git+https://github.com/Tianwen10532/dtw.git;
                ulimit -n 65536; echo worker; $KUBERAY_GEN_RAY_START_CMD
                tail -f /dev/null
            resources:
              requests:
                cpu: "1"
                
  # runtimeEnvYAML: |
  #   pip:
  #     - requests==2.26.0
  #     - pendulum==2.1.2
  #   env_vars:
  #     counter_name: "test_counter"
  shutdownAfterJobFinishes: true
  submissionMode: K8sJobMode
  ttlSecondsAfterFinished: 10